FROM oven/bun:latest

WORKDIR /
RUN apt-get -y update; apt-get -y install curl
ARG NODE_VERSION=18
RUN curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n \
    && bash n $NODE_VERSION \
    && rm n \
    && npm install -g n

COPY package*.json bun.lockb ./

RUN bun install

COPY . .

RUN npx prisma generate

EXPOSE 3001
CMD ["bun", "run", "index.ts"]