-- AlterTable
ALTER TABLE "Decision" ALTER COLUMN "start_time" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "end_time" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Party" ALTER COLUMN "end_time" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "start_time" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TimeSlot" ALTER COLUMN "start_time" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "end_time" SET DATA TYPE DOUBLE PRECISION;
